version: "3"

services:
  db:
    container_name: Reception-Register-DB
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb:/data/db

  api:
    build: ./reception_register_api
    container_name: Reception-Register-API
    depends_on:
      - db
    image: reception-register:api
    restart: always

  webui:
    build: ./reception_register_webui
    container_name: Reception-Register-WEBUI
    depends_on:
      - db
    image: reception-register:webui
    restart: on-failure
    volumes:
      - ./reception_register_webui/dist:/app/dist

  proxy:
    container_name: Reception-Register-PROXY
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - ./reception_register_webui/dist:/var/www/html
